#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_


#define VERSION "1.1.0"


//Display
#define DISPLAY_WIDTH 160
#define DISPLAY_HEIGHT 160

#define DISPLAY_OFFSET_X 0
#define DISPLAY_OFFSET_Y 0
#define DISPLAY_MIRROR_X false
#define DISPLAY_MIRROR_Y false
#define DISPLAY_SWAP_XY false

#define DISPLAY_SPI SPI3_HOST
#define DISPLAY_MOSI GPIO_NUM_37
#define DISPLAY_SCLK GPIO_NUM_38
#define DISPLAY_DC GPIO_NUM_40
#define DISPLAY_RST GPIO_NUM_36
#define DISPLAY_CS GPIO_NUM_39
//BACKLIGHT 
#define DISPLAY_BACKLIGHT_TIMER LEDC_TIMER_0
#define DISPLAY_BACKLIGHT_CHANNEL LEDC_CHANNEL_0
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_41
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

//AXP2101
#define AXP_I2C I2C_NUM_0
#define AXP_I2C_INT_PIN GPIO_NUM_17
#define AXP_I2C_SDA_PIN  GPIO_NUM_16
#define AXP_I2C_SCL_PIN  GPIO_NUM_15
#define AXP2101_I2C_ADDR 0x34

//Joystick
#define JOYSTICK_CHANNEL_0 ADC_CHANNEL_0
#define JOYSTICK_CHANNEL_1 ADC_CHANNEL_1
#define JOYSTICK_CHANNEL_2 ADC_CHANNEL_7
#define JOYSTICK_CHANNEL_3 ADC_CHANNEL_8

//MATRIX_KEYBOARD
#define MATRIX_KEYBOARD_ROWS (int[]){3, 18, 14, 5, 21}
#define MATRIX_KEYBOARD_COLS (int[]){11, 4, 13, 12}
#define MATRIX_KEYBOARD_ROWS_NUM 5
#define MATRIX_KEYBOARD_COLS_NUM 4

//TOUCH
#define TOUCH  GPIO_NUM_10

//ROTARY
#define EC_P  GPIO_NUM_46
#define EC_N  GPIO_NUM_45

//IMU
#define ICM_TIMER LEDC_TIMER_1
#define ICM_TIMER_CHANNEL0 LEDC_CHANNEL_1
#define ICM_INT0  GPIO_NUM_6
#define ICM_SPI SPI2_HOST
#define ICM_SDO  GPIO_NUM_35
#define ICM_SDI  GPIO_NUM_34
#define ICM_SCK  GPIO_NUM_33
#define ICM_CS0   GPIO_NUM_7
// #define ICM_CS1   GPIO_NUM_47
// #define ICM_INT1  GPIO_NUM_48

//haptic motor
#define HAPTIC_TIMER LEDC_TIMER_2
#define HAPTIC_TIMER_CHANNEL_L LEDC_CHANNEL_3
#define HAPTIC_TIMER_CHANNEL_R LEDC_CHANNEL_4
#define HAPTIC_MOTOR_L  GPIO_NUM_0
#define HAPTIC_MOTOR_R  GPIO_NUM_42



#define CFG_PRESS_DEBOUNCE 10
#define CFG_HOLD_TIME 200  // Milliseconds.
#define CFG_HOLD_LONG_TIME 2000  // Milliseconds.
#define CFG_DOUBLE_PRESS_TIME 300  // Milliseconds.

#endif // _BOARD_CONFIG_H_
